services:
  - type: web
    name: tcdd-bilet-takip
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
